=== QuestPackageManager/bsqmods/source/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["id", "version"],
        "additionalProperties": false
      }
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*\\.(gif|jpg|jpeg|png)$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "ai": {
      "type": "string",
      "enum": ["none", "assisted", "fully-vibed"]
    }
  },
  "required": ["name", "description", "id", "version", "author", "authorIcon", "modloader", "download", "dependencies", "source", "cover", "funding", "website"]
}

=== QuestPackageManager/bsqmods/mods/1.45.0_26420/songcore-1.3.2.json
{
  "name": "SongCore",
  "description": "Adds songloading, map requirement handling and related utilities to the game.",
  "id": "songcore",
  "version": "1.3.2",
  "author": "Raine & RedBrumbler",
  "authorIcon": "https://avatars.githubusercontent.com/u/64136899?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/raineaeternal/Quest-SongCore/releases/download/v1.3.2/SongCore.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^8.0.1"
    },
    {
      "id": "bsml",
      "version": "^0.5.5"
    },
    {
      "id": "custom-types",
      "version": "^0.20.0"
    },
    {
      "id": "flamingo",
      "version": "^1.1.2"
    },
    {
      "id": "lapiz",
      "version": "^0.3.5"
    },
    {
      "id": "metacore",
      "version": "^2.0.3"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.7.0"
    }
  ],
  "source": "https://github.com/raineaeternal/Quest-SongCore/",
  "cover": "https://raw.githubusercontent.com/raineaeternal/Quest-SongCore/main/cover.jpg",
  "funding": [],
  "website": "https://github.com/raineaeternal/Quest-SongCore/"
}

=== QuestPackageManager/bsqmods/mods/1.17.1/FingerSaber-0.1.1.json
{
  "name": "FingerSaber",
  "description": "Beat Saber At Your Finger Tips. @drumtool#4435",
  "id": "FingerSaber",
  "version": "0.1.1",
  "author": "Henri",
  "authorIcon": "https://avatars.githubusercontent.com/u/38835729?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/im-henri/FingerSaber/releases/download/v0.1.1/FingerSaber_v0.1.1.qmod",
  "dependencies": [],
  "source": "https://github.com/im-henri/FingerSaber/",
  "cover": "https://raw.githubusercontent.com/im-henri/FingerSaber/main/cover.jpg",
  "funding": [],
  "website": null
}

=== QuestPackageManager/bsqmods/mods/global/beatsaber-hook-9.2.0.json
{
  "name": "beatsaber-hook",
  "description": "Provides modding utilities for unity il2cpp games",
  "id": "beatsaber-hook",
  "version": "9.2.0",
  "author": "sc2ad",
  "authorIcon": "https://avatars.githubusercontent.com/u/110287845?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/QuestPackageManager/beatsaber-hook/releases/download/v9.2.0/beatsaber-hook.qmod",
  "dependencies": [
    {
      "id": "flamingo",
      "version": "^1.2.1"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.4.0"
    }
  ],
  "source": "https://github.com/QuestPackageManager/beatsaber-hook/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/QuestPackageManager/beatsaber-hook/"
}

=== QuestPackageManager/bsqmods/mods/1.24.0/chatui-0.2.8.json
{
  "name": "ChatUI",
  "description": "Shows your Twitch Chat Ingame",
  "id": "chatui",
  "version": "0.2.8",
  "author": "darknight1050",
  "authorIcon": "https://avatars.githubusercontent.com/u/18632205?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/darknight1050/ChatUI/releases/download/v0.2.8/ChatUI.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.25.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.18"
    },
    {
      "id": "questui",
      "version": "^0.16.4"
    }
  ],
  "source": "https://github.com/darknight1050/ChatUI/",
  "cover": "https://raw.githubusercontent.com/darknight1050/ChatUI/master/cover.png",
  "funding": [],
  "website": null
}

=== QuestPackageManager/bsqmods/mods/1.17.0/songloader-0.7.0.json
{
  "name": "SongLoader",
  "description": null,
  "id": "songloader",
  "version": "0.7.0",
  "author": "darknight1050",
  "authorIcon": "https://avatars.githubusercontent.com/u/18632205?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/darknight1050/SongLoader/releases/download/v0.7.0/songloader.qmod",
  "dependencies": [],
  "source": "https://github.com/darknight1050/SongLoader/",
  "cover": "https://raw.githubusercontent.com/darknight1050/SongLoader/main/cover.png",
  "funding": [],
  "website": null
}

=== QuestPackageManager/bsqmods/mods/1.40.8_7379/FakeId-0.1.9.json
{
  "name": "Fake ID",
  "description": "Sets the player age to an adult.",
  "id": "FakeId",
  "version": "0.1.9",
  "author": "DanTheMan827",
  "authorIcon": "https://avatars.githubusercontent.com/u/176073241?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/DanTheMan827-BeatSaber/Quest.FakeID/releases/download/v0.1.9%2B1.40.8_7379/Fake.ID.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.6.4"
    }
  ],
  "source": "https://github.com/DanTheMan827-BeatSaber/Quest.FakeID/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/DanTheMan827-BeatSaber/Quest.FakeID/"
}

=== QuestPackageManager/bsqmods/mods/1.45.3_30054/MyTemplateModId-0.1.3.json
{
  "name": "MyTemplateModName",
  "description": "MyTemplateModDescription",
  "id": "MyTemplateModId",
  "version": "0.1.3",
  "author": "MyTemplateModAuthor",
  "authorIcon": "https://avatars.githubusercontent.com/u/176073241?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/DanTheMan827-BeatSaber/mod-template/releases/download/v0.1.3/MyTemplateModName.qmod",
  "source": "https://github.com/DanTheMan827-BeatSaber/mod-template/",
  "cover": null,
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^9.3.0"
    },
    {
      "id": "flamingo",
      "version": "^1.2.1"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.8.0"
    }
  ],
  "funding": [],
  "website": "https://github.com/DanTheMan827-BeatSaber/mod-template/"
}

=== QuestPackageManager/bsqmods/mods/1.35.0_8016709773/MappingExtensions-0.23.1.json
{
  "name": "Mapping Extensions",
  "description": "This adds a host of new things you can do with your maps as a mapper, and allows you to play said maps as a player. An update of the port of the PC original mod by Kyle 1413. Previously maintained by zoller27osu.",
  "id": "MappingExtensions",
  "version": "0.23.1",
  "author": "StackDoubleFlow, rxzz0, & rcelyte",
  "authorIcon": "https://avatars.githubusercontent.com/u/25163630?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/rcelyte/MappingExtensions/releases/download/0.23.1/MappingExtensions.qmod",
  "dependencies": [
    {
      "id": "paper",
      "version": "^3.6.1"
    },
    {
      "id": "songcore",
      "version": "^1.0.0"
    }
  ],
  "source": "https://github.com/rcelyte/MappingExtensions/",
  "cover": "https://raw.githubusercontent.com/rcelyte/MappingExtensions/master/cover.png",
  "funding": [],
  "website": null
}
