=== QuestPackageManager/bsqmods/source/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["id", "version"],
        "additionalProperties": false
      }
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*\\.(gif|jpg|jpeg|png)$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "ai": {
      "type": "string",
      "enum": ["none", "assisted", "fully-vibed"]
    }
  },
  "required": ["name", "description", "id", "version", "author", "authorIcon", "modloader", "download", "dependencies", "source", "cover", "funding", "website"]
}

=== QuestPackageManager/bsqmods/mods/1.40.4_5283/too-many-fireworks-1.2.2.json
{
  "name": "TooManyFireworks",
  "description": "Don't think there's enough fireworks? This mod adds a variety of settings that can make fireworks powerful enough to explode the game itself!",
  "id": "too-many-fireworks",
  "version": "1.2.2",
  "author": "CatsaCode",
  "authorIcon": "https://avatars.githubusercontent.com/u/155121307?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/CatsaCode/TooManyFireworks/releases/download/v1.2.2/TooManyFireworks.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.1"
    },
    {
      "id": "bsml",
      "version": "^0.4.51"
    },
    {
      "id": "custom-types",
      "version": "^0.18.2"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.6.1"
    }
  ],
  "source": "https://github.com/CatsaCode/TooManyFireworks/",
  "cover": "https://raw.githubusercontent.com/CatsaCode/TooManyFireworks/main/cover.png",
  "funding": [],
  "website": "https://github.com/CatsaCode/TooManyFireworks/"
}

=== QuestPackageManager/bsqmods/mods/1.24.0/peripheralhud-1.0.0.json
{
  "name": "PeripheralHUD",
  "description": "Move your in-game HUD into your peripheral vision, allowing for easy at-a-glance viewing of your combo, score, etc!",
  "id": "peripheralhud",
  "version": "1.0.0",
  "author": "Kaitlyn",
  "authorIcon": "https://avatars.githubusercontent.com/u/87990853?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/whatdahopper-archive/PeripheralHUD/releases/download/v1.0.0/peripheralhud_v1.0.0.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "^0.25.0"
    },
    {
      "id": "custom-types",
      "version": "^0.15.18"
    },
    {
      "id": "questui",
      "version": "^0.16.4"
    }
  ],
  "source": "https://github.com/whatdahopper-archive/PeripheralHUD/",
  "cover": "https://raw.githubusercontent.com/whatdahopper-archive/PeripheralHUD/main/cover.png",
  "funding": [],
  "website": null
}

=== QuestPackageManager/bsqmods/mods/1.40.8_7379/bsl-1.0.8.json
{
  "name": "Better Song List",
  "description": "Improvement upon SongBrowser with similiar functionality",
  "id": "bsl",
  "version": "1.0.8",
  "author": "RedBrumbler, Pink, Kinsi55",
  "authorIcon": "https://avatars.githubusercontent.com/u/80212088?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/bsq-ports/BetterSongList/releases/download/v1.0.8-bs-1.40.8/BetterSongList.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "bsml",
      "version": "^0.4.55"
    },
    {
      "id": "custom-types",
      "version": "^0.18.3"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.8.0"
    },
    {
      "id": "playlistcore",
      "version": "^1.5.5"
    },
    {
      "id": "song-details",
      "version": "^1.0.5"
    },
    {
      "id": "songcore",
      "version": "^1.1.24"
    }
  ],
  "source": "https://github.com/bsq-ports/BetterSongList/",
  "cover": "https://raw.githubusercontent.com/bsq-ports/BetterSongList/main/cover.jpg",
  "funding": [],
  "website": "https://github.com/bsq-ports/BetterSongList/"
}

=== QuestPackageManager/bsqmods/mods/1.27.0_3631150051/smoothedcontroller-1.5.1.json
{
  "name": "Smoothed Controller",
  "description": "Smoothes your Controller position while in menus to make it less shaky, making the UI easier to use, etc.",
  "id": "smoothedcontroller",
  "version": "1.5.1",
  "author": "Kinsi55, Kaitlyn",
  "authorIcon": "https://avatars.githubusercontent.com/u/87990853?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/whatdahopper-archive/SmoothedController/releases/download/v1.5.1/smoothedcontroller_v1.5.1.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "=0.32.0"
    },
    {
      "id": "custom-types",
      "version": "=0.15.22"
    },
    {
      "id": "questui",
      "version": "=0.17.10"
    }
  ],
  "source": "https://github.com/whatdahopper-archive/SmoothedController/",
  "cover": null,
  "funding": [],
  "website": null
}

=== QuestPackageManager/bsqmods/mods/1.25.1/morebycore-1.3.1.json
{
  "name": "More By Core",
  "description": "More By Core, for 1.25.1! Lets you customize BeatSaber with added stuff!",
  "id": "morebycore",
  "version": "1.3.1",
  "author": "Core",
  "authorIcon": "https://avatars.githubusercontent.com/u/83958883?v=4",
  "modloader": "QuestLoader",
  "download": "https://github.com/Core-Quest/MoreByCore/releases/download/v1.3.1/MoreByCore.qmod",
  "dependencies": [
    {
      "id": "codegen",
      "version": "*"
    },
    {
      "id": "custom-types",
      "version": "*"
    },
    {
      "id": "questui",
      "version": "*"
    }
  ],
  "source": "https://github.com/Core-Quest/MoreByCore/",
  "cover": null,
  "funding": [],
  "website": null
}

=== QuestPackageManager/bsqmods/mods/1.13.2/goodbyebug-0.1.4.json
{
  "name": "GoodbyeBug",
  "description": "Fixes playlist scrolling in the wrong direction when you got more than 8 playlists",
  "id": "goodbyebug",
  "version": "0.1.4",
  "author": "Rugtveit",
  "authorIcon": null,
  "modloader": "QuestLoader",
  "download": "https://github.com/Rugtveit/GoodbyeBug/releases/download/0.1.4/GoodbyeBug.zip",
  "dependencies": [],
  "source": "https://github.com/Rugtveit/GoodbyeBug",
  "cover": null,
  "funding": [],
  "website": "https://github.com/Rugtveit/GoodbyeBug"
}

=== QuestPackageManager/bsqmods/mods/1.40.8_7379/discordrichpresence-0.1.5.json
{
  "name": "Discord Rich Presence",
  "description": "A Beat Saber Quest mod for displaying stats on Discord",
  "id": "discordrichpresence",
  "version": "0.1.5",
  "author": "Jess",
  "authorIcon": "https://avatars.githubusercontent.com/u/62964686?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/RainzDev/BSQ_DiscordRichPresence/releases/download/v0.1.5/DiscordRichPresence.qmod",
  "dependencies": [],
  "source": "https://github.com/RainzDev/BSQ_DiscordRichPresence/",
  "cover": "https://raw.githubusercontent.com/RainzDev/BSQ_DiscordRichPresence/main/cover.jpg",
  "funding": [],
  "website": "https://github.com/RainzDev/BSQ_DiscordRichPresence/"
}

=== QuestPackageManager/bsqmods/mods/1.45.0_26420/bsml-0.6.0.json
{
  "name": "BSML",
  "description": "Library that parses BeatSaber Markup Language to create UI elements",
  "id": "bsml",
  "version": "0.6.0",
  "author": "RedBrumbler",
  "authorIcon": "https://avatars.githubusercontent.com/u/80212088?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/bsq-ports/Quest-BSML/releases/download/v0.6.0/BSML.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^8.0.1"
    },
    {
      "id": "custom-types",
      "version": "^0.20.2"
    },
    {
      "id": "flamingo",
      "version": "^1.2.1"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.8.0"
    },
    {
      "id": "tinyxml2",
      "version": "^10.0.0"
    }
  ],
  "source": "https://github.com/bsq-ports/Quest-BSML/",
  "cover": "https://raw.githubusercontent.com/bsq-ports/Quest-BSML/master/cover.png",
  "funding": [],
  "website": "https://github.com/bsq-ports/Quest-BSML/"
}
