=== QuestPackageManager/bsqmods/source/shared/schemas/Mod.schema.base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Mod.schema.base.json",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "flags": "i"
    },
    "author": {
      "type": ["string", "null"]
    },
    "authorIcon": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "modloader": {
      "type": "string",
      "enum": ["QuestLoader", "Scotland2"]
    },
    "download": {
      "type": "string",
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "version": { "type": "string" }
        },
        "required": ["id", "version"],
        "additionalProperties": false
      }
    },
    "source": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "cover": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*\\.(gif|jpg|jpeg|png)$",
      "flags": "i"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "pattern": "^(http|https)://.*$",
        "flags": "i"
      }
    },
    "website": {
      "type": ["string", "null"],
      "format": "uri",
      "pattern": "^(http|https)://.*$",
      "flags": "i"
    },
    "ai": {
      "type": "string",
      "enum": ["none", "assisted", "fully-vibed"]
    }
  },
  "required": ["name", "description", "id", "version", "author", "authorIcon", "modloader", "download", "dependencies", "source", "cover", "funding", "website"]
}

=== QuestPackageManager/bsqmods/mods/global/bs-utils-0.8.4.json
{
  "name": "bs-utils",
  "description": "Utils library",
  "id": "bs-utils",
  "version": "0.8.4",
  "author": "Sc2ad",
  "authorIcon": "https://avatars.githubusercontent.com/u/51795403?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/RedBrumbler/QuestBS-Utils/releases/download/v0.8.4/BS-Utils.qmod",
  "dependencies": [
    {
      "id": "paper",
      "version": "^3.6.3"
    }
  ],
  "source": "https://github.com/RedBrumbler/QuestBS-Utils/",
  "cover": "https://raw.githubusercontent.com/RedBrumbler/QuestBS-Utils/master/cover.png",
  "funding": [],
  "website": "https://github.com/RedBrumbler/QuestBS-Utils/"
}

=== QuestPackageManager/bsqmods/mods/1.40.8_7379/discordrichpresence-0.3.4.json
{
  "name": "Discord Rich Presence",
  "description": "A Beat Saber Quest mod for displaying stats on Discord",
  "id": "discordrichpresence",
  "version": "0.3.4",
  "author": "Jess",
  "authorIcon": "https://avatars.githubusercontent.com/u/62964686?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/RainzDev/BSQ_DiscordRichPresence/releases/download/v0.3.4/DiscordRichPresence.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "beatsaverplusplus",
      "version": "^0.2.4"
    },
    {
      "id": "bsml",
      "version": "^0.4.9"
    },
    {
      "id": "custom-types",
      "version": "^0.18.4"
    },
    {
      "id": "metacore",
      "version": "^1.6.3"
    },
    {
      "id": "morebuttons",
      "version": "*"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.8.0"
    },
    {
      "id": "web-utils",
      "version": "^0.6.8"
    }
  ],
  "source": "https://github.com/RainzDev/BSQ_DiscordRichPresence/",
  "cover": "https://raw.githubusercontent.com/RainzDev/BSQ_DiscordRichPresence/main/cover.jpg",
  "funding": [],
  "website": "https://github.com/RainzDev/BSQ_DiscordRichPresence/"
}

=== QuestPackageManager/bsqmods/mods/global/socket_lib-0.11.1.json
{
  "name": "SocketLib",
  "description": "socket_lib, version 0.11.1!",
  "id": "socket_lib",
  "version": "0.11.1",
  "author": "Fernthedev",
  "authorIcon": "https://avatars.githubusercontent.com/u/15272073?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/Fernthedev/SocketLibLinux/releases/download/v0.11.1/socket_lib.qmod",
  "dependencies": [
    {
      "id": "paper",
      "version": "^3.6.4"
    }
  ],
  "source": "https://github.com/Fernthedev/SocketLibLinux/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/Fernthedev/SocketLibLinux/"
}

=== QuestPackageManager/bsqmods/mods/global/song-details-0.3.7.json
{
  "name": "SongDetails",
  "description": "Library that provides details about songs from BeatSaver",
  "id": "song-details",
  "version": "0.3.7",
  "author": "RedBrumbler",
  "authorIcon": "https://avatars.githubusercontent.com/u/80212088?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/bsq-ports/SongDetails/releases/download/v0.3.7/SongDetails.qmod",
  "dependencies": [
    {
      "id": "paper",
      "version": "^3.6.3"
    }
  ],
  "source": "https://github.com/bsq-ports/SongDetails/",
  "cover": null,
  "funding": [],
  "website": "https://github.com/bsq-ports/SongDetails/"
}

=== QuestPackageManager/bsqmods/mods/1.45.0_26420/mod-list-0.2.8.json
{
  "name": "ModList",
  "description": "Displays your installed mods inside the game and gives you a warning prompt upon starting the game to tell you if a mod failed to load.",
  "id": "mod-list",
  "version": "0.2.8",
  "author": "Lauriethefish",
  "authorIcon": "https://avatars.githubusercontent.com/u/176073241?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/DanTheMan827-BeatSaber/Quest.ModList/releases/download/v0.2.8%2B1.45.0_26420/ModList.qmod",
  "source": "https://github.com/DanTheMan827-BeatSaber/Quest.ModList/",
  "cover": null,
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^8.0.7"
    },
    {
      "id": "bsml",
      "version": "^0.5.8"
    },
    {
      "id": "custom-types",
      "version": "^0.20.0"
    },
    {
      "id": "flamingo",
      "version": "^1.2.1"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.8.0"
    },
    {
      "id": "reflectcpp",
      "version": "^0.25.0"
    }
  ],
  "funding": [],
  "website": "https://github.com/DanTheMan827-BeatSaber/Quest.ModList/"
}

=== QuestPackageManager/bsqmods/mods/1.40.8_7379/qounters++-1.1.3.json
{
  "name": "Qounters++",
  "description": "Add endlessly customizable counters to your ingame UI!",
  "id": "qounters++",
  "version": "1.1.3",
  "author": "Metalit",
  "authorIcon": "https://avatars.githubusercontent.com/u/48568911?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/Metalit/Qounters/releases/download/v1.1.3/Qounters%2B%2B.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "bsml",
      "version": "^0.4.55"
    },
    {
      "id": "custom-types",
      "version": "^0.18.3"
    },
    {
      "id": "metacore",
      "version": "^1.6.3"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.6.4"
    },
    {
      "id": "songcore",
      "version": "^1.1.24"
    }
  ],
  "source": "https://github.com/Metalit/Qounters/",
  "cover": "https://raw.githubusercontent.com/Metalit/Qounters/main/cover.png",
  "funding": [],
  "website": "https://github.com/Metalit/Qounters/"
}

=== QuestPackageManager/bsqmods/mods/1.37.0_9064817954/crashreporter-0.1.12.json
{
  "name": "CrashReporter",
  "description": "Automatically upload crashes.",
  "id": "crashreporter",
  "version": "0.1.12",
  "author": "darknight1050",
  "authorIcon": "https://avatars.githubusercontent.com/u/18632205?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/darknight1050/CrashReporter/releases/download/v0.1.12/CrashReporter.qmod",
  "dependencies": [
    {
      "id": "bsml",
      "version": "^0.4.43"
    },
    {
      "id": "custom-types",
      "version": "^0.17.10"
    },
    {
      "id": "paper",
      "version": "^3.6.3"
    }
  ],
  "source": "https://github.com/darknight1050/CrashReporter/",
  "cover": "https://raw.githubusercontent.com/darknight1050/CrashReporter/master/cover.png",
  "funding": [],
  "website": "https://github.com/darknight1050/CrashReporter/"
}

=== QuestPackageManager/bsqmods/mods/1.40.8_7379/KeepFavorites-0.1.2.json
{
  "name": "Keep Favorites",
  "description": "Scans custom songs on Quest Beat Saber and deletes non-favorite song folders from an in-game UI.",
  "id": "KeepFavorites",
  "version": "0.1.2",
  "author": "TigerYoo",
  "authorIcon": "https://avatars.githubusercontent.com/u/6271133?v=4",
  "modloader": "Scotland2",
  "download": "https://github.com/MTGVim/beatsaber-keep-favorites/releases/download/v0.1.2/KeepFavorites.qmod",
  "dependencies": [
    {
      "id": "beatsaber-hook",
      "version": "^6.4.2"
    },
    {
      "id": "bsml",
      "version": "^0.4.55"
    },
    {
      "id": "custom-types",
      "version": "^0.18.4"
    },
    {
      "id": "paper2_scotland2",
      "version": "^4.7.0"
    },
    {
      "id": "songcore",
      "version": "^1.1.25"
    }
  ],
  "source": "https://github.com/MTGVim/beatsaber-keep-favorites/",
  "cover": "https://raw.githubusercontent.com/MTGVim/beatsaber-keep-favorites/main/assets/readme-cover.png",
  "funding": [],
  "website": "https://github.com/MTGVim/beatsaber-keep-favorites/"
}
